### ISSUE TITLE
Consider human-friendly API for roles/permissions

### ISSUE THREAD

**Issue by brylie** [Meteor-Community-Packages/meteor-roles#169]
This is a continuation of the discussion in issue #114.
# User stories

```
As a developer
I need a 'human-friendly' API for defining roles and permissions
in order to clearly reason about and communicate my system permissions model
```

```
As a developer
I would like to write code as close to a 'literate' style as possible
so that it is easier to read while minimising language-driven semantics
```
# Opportunity

The current `Roles()` API mixes concepts of roles and permissions. While it is designed to provide flexible and hierarchical Roles, the mixed semantics do not clearly communicate the purpose of roles. The over-use of the word Role, leads developers to design 'illiterate' code, or code that can not be directly read as if reading a paragraph or sentence of human-language. In effect, the code is read with JavaScript semantics and practicalities taking precedence over clarity and semantics.
# Idea

This issue is a challenge to take the opportunity and design a semantic, human-first API for access control. There are examples in other libraries that may be freely used and evolved to suit the purpose of this project, some of which are outlined below.
## Example, or pseudo, API

The following code snippets demonstrate an example API, by which people could describe and define access control rules relevant to their organization/process. Permissions can be defined using semantics that are very close to plain language:
### Allow().Role()

``` js
// Allow moderators to delete comments
Allow("deleteComments").Role("moderators");
```
### Role().can()

Roles can perform certain actions. E.g. _"Moderators can delete"_

``` js
Role("moderators").can("deleteComments"); // Returns true
```

`Role.can()` may also be used as a setter:

``` js
// Allow moderators to delete comments, by setting to true
Role("moderators").can("deleteComments", true); 
```
# Resources

The following resources are the basis of the terms 'human-friendly' and 'literate':
- [Human JavaScript](http://read.humanjavascript.com/) by Henrik Joreteg
- [Literate programming](https://en.wikipedia.org/wiki/Literate_programming) by Donald Knuth

The following resources and libraries demonstrate attempts at creating Literate, or human-friendly, software APIs:
- [ability.js](https://github.com/scottkf/ability-js) has a role/permissions approach, that may be complementary to this idea and package.
- [Towards re-usable charts](http://bost.ocks.org/mike/chart/) by Mike Bostock
- [Later.js](http://bunkat.github.io/later/index.html) - human-friendly recurring events in declarative style

**Comment by alanning** [comment]
@brylie, Thanks for following through with this!  I do like the proposed style.

One of the goals of Roles 2.0 is to allow everyone to more easily build on top of the roles base package with their own extension package.  This seems like an excellent extension and I'd suggest that you attempt to make this happen in your own package.  We can add a section to our readme highlighting your package and send traffic/users your way.

If you do run into issues basing it on Roles 2.0 then let us know and we'll fix the underlying problem.

What do you think?

**Comment by rhyslbw** [comment]
I'd use your package @brylie :+1:

**Comment by brylie** [comment]
@alanning thanks for the suggestion. Is there a 'extending Roles' guide, or something similar?

@rhyslbw thanks for the encouragement :-)

**Comment by rhyslbw** [comment]
cc @darko-mijic

**Comment by alanning** [comment]
There's no guide as of now.

For your proposed addition, I think you can do a pass though to the
existing roles functions. You may want to do some automatic checks to make
sure the parent role is already created.

I'd also recommend taking a look at the new schema in roles 2.0 just to
understand how things are stored.

Personally, I like the "Role.can()" syntax.

**Comment by brylie** [comment]
After reading a bit further, I think we are describing what is similar to a [fluent programming interface](https://en.wikipedia.org/wiki/Fluent_interface. We [may not need to strictly follow a fluent interface for method chaining](http://ocramius.github.io/blog/fluent-interfaces-are-evil/), but the surface of the API seems to have a similar **goal of improving code readability**.

**Comment by mitar** [comment]
Yes, in this case I think you can simply create your own top-level symbol which calls roles underneath. So this extension probably does not have to change anything in the logic of roles.

For roles which do have to change the logic my current proposal would be to monkey-patch/wrap existing methods. If some method is too rigid or too big, we can split it if needed into smaller.

**Comment by jedwards1211** [comment]
What does `Allow("deleteComments").Role("moderators");` technically mean?  Does it mean make "moderators" a parent role of the "deleteComments" role?

**Comment by brylie** [comment]
Well, that is one interpretation, and perhaps a limitation of a strict hierarchical roles system. This is why I am proposing that roles and permissions be considered as separate, but related entities. Then there can be a many to many relationship between roles and permissions

**Comment by mitar** [comment]
So I labeled this as a 3rd party extension. I think alternative APIs could be a great package building on top of this.

**Comment by jedwards1211** [comment]
@brylie There's no actual limitation to its functionality. Roles can represent either permissions or groups of permissions if you want, which may be a bit confusing, but it can to do everything a system with separate roles and permissions can do, and has the advantage of being simpler.  Not to mention that since you can have arbitrary levels of roles of roles, you can make supergroups of permissions and so forth.  Roles have a many to many relationship with themselves.

**Comment by deepupathak** [comment]
Is there any way to assign roles through UI ?
I want to input roles through the users from form and then store that role in users collection (field name:- roles;[ ]). Is it possible ?

thanks in advance.

**Comment by brylie** [comment]
We have a [user management UI package](https://github.com/apinf/meteor-accounts-admin-ui-bootstrap-3/) that allows you to assign user roles via a Bootstrap 3 user interface. Let us know if we can improve the package to meet your needs.

**Comment by mitar** [comment]
Closing in favor of a 3rd party extension here.
