### ISSUE TITLE
[V2.0] bulk declaration of roles and relations between them

### ISSUE THREAD

**Issue by jsamr** [Meteor-Community-Packages/meteor-roles#173]
The idea is to express the hierarchy in one place, with the advantage of a visual representation, and possibly a declaration in your meteor JSON config file. I chose `setSchema` but perhaps a less ambiguous method name could be `setModel`, since schema is often associated with data bases. Any name suggestion is welcome! 

``` javascript
Roles.declare({
  'admin':{
    'POST_EDIT': null, // <- no children
    'user': {
        'USERS_VIEW': null // <- no children
    }
  }
})
```

This shema means any role a user has, the admin will have it too. 
Now an other way to express it, closer to `README.md` example : 

``` javascript
Roles.declare({
  'admin':{
    'POST_EDIT': null, // <- no children
    'USERS_VIEW': null // <- no children
  },
  'user': {
    'USERS_VIEW': null // <- no children
  }
})
```

As @mitar suggested, this "model" application would drop any relationship that does not conform.

**OLD PROPOSITION (ABANDONED)**
Example : 

``` javascript
Roles.setSchema({
  'admin':[
    { 
     'user':'USERS_VIEW'
    },
    'POST_EDIT'
  ]
})
```

Would do the following : 

``` javascript
Roles.createRole('admin');
Roles.createRole('user');
Roles.createRole('USERS_VIEW');
Roles.createRole('POST_EDIT');
Roles.addRolesToParent('USERS_VIEW', 'user');
Roles.addRolesToParent('user', 'admin');
Roles.addRolesToParent('POST_EDIT', 'admin');
```

Rules are following : 
- an array contains a set of children. A child has to be a leaf (string) or a set of nodes (plain object)
- a string value is a leaf (bottom-end of your tree)
- a plain object value is a set of nodes

**Comment by mitar** [comment]
I do not know what this is. But I do not think so.

**Comment by sveinburne** [comment]
Well the idea is to set your hierarchy schema in one place, with the advantage of a visual representation, and possibly a declaration in your meteor JSON config file. Rules are following : 

* an array contains a set of children. A child has to be a leaf (string) or a set of nodes (plain object)
* a string value is a leaf (bottom-end of your tree)
* a plain object value is a set of nodes

But I agree it's not super pretty. Perhaps with the following : 

```javascript 
Roles.setSchema({
  'admin':{
    'POST_EDIT': null, // <- no children
    'user': {
        'USERS_VIEW': null // <- no children
    }
  }
})
``` 

This shema means any role a user has, the admin will have it too. 
Now an other way to express it, closer to `README.md` example : 
```javascript 
Roles.setSchema({
  'admin':{
    'POST_EDIT': null, // <- no children
    'USERS_VIEW': null // <- no children
  },
  'user': {
    'USERS_VIEW': null // <- no children
  }
})
```

**Comment by mitar** [comment]
Ah, OK. I was confused by the name "schema". Yes, such a helper could be useful. Probably you also want to drop anything which does not conform to this "schema". So if you are changing it. Not just add new stuff.

I think this could be useful for an extra package though.

**Comment by sveinburne** [comment]
Cool! Perhaps a less ambiguous name like `model` instead of `schema` ?
If you're OK I'll just edit my first post and delete my second to clean up the post.

**Comment by mitar** [comment]
Yes, feel free to clean-it up. You can also make a line with original post and put edited content below or above.

I am bad with naming, so let's leave to others to help here.

**Comment by flippyhead** [comment]
Did you guys consider using simple-schema here instead? It's become something MDG is behind now and provides standard semantics for doing exactly this kind of thing. It's totally independent of collections or the database too.

**Comment by mitar** [comment]
This is completely unrelated. This is why I do not like "schema" in the title of this issue.

**Comment by mitar** [comment]
Closing in favor of making this a 3rd party extension.
