### ISSUE TITLE
User is in a role in any group?

### ISSUE THREAD

**Issue by oliverthomasklein** [Meteor-Community-Packages/meteor-roles#190]
Let say i have a user that has been given the role practiceOwner for a specific ID as the group.

`Roles.addUsersToRoles(userIdToAssign, ['practiceOwner'], idToAssign);`

Is there a way to test for the specific role of practiceOwner for any ID without having to pass in a specific id?

Something like:
`Roles.userIsInRole(userIdToAssign, 'practiceOwner');`

Or
`Roles.userIsInRole(userIdToAssign, 'practiceOwner', *);`

Right now i have a general role as owner which is in the global group but this is leading some awkward edge cases. Any help would be much appreciated, thank you!

**Comment by mitar** [comment]
Closing this for now as it is very old.
