### ISSUE TITLE
I was using this on the server

### ISSUE THREAD

**Issue by reduxdj** [Meteor-Community-Packages/meteor-roles#200]
Roles.addUsersToRoles and it's complement do not have a return value, consider returning a 1 the operation succeeds.

**Comment by mitar** [comment]
Can you elaborate? I do not understand what you are saying here.

**Comment by s-devaney** [comment]
+1

addUsersToRoles should return true/false

**Comment by mitar** [comment]
And what should be returned if some users are added to roles, but some are not?

What is use case for this? Why do you need this/

**Comment by mitar** [comment]
Closing because of no response.
