### ISSUE TITLE
Consider promise or callback for db operation complete.

### ISSUE THREAD

**Issue by myexampleusername** [Meteor-Community-Packages/meteor-roles#201]
There's times when updating a user's role will merit a redirect given new permissions, but without a promise or callback for write operations on updating roles, it's difficult to know when the role has been written to the db such that a router can appropriately route!

Added a promise or callback to your API shouldn't break backwards compatibility.

Thanks!

**Comment by mitar** [comment]
In 2.0 you should just use functions inside the Meteor method. When the Meteor method returns, you know that it finished.

**Comment by mitar** [comment]
Calling API methods outside of Meteor methods is discouraged.

**Comment by myexampleusername** [comment]
@mitar I'm actually not calling API methods outside of Meteor methods.  Can you show a code example of what you're talking about, 2 comments above? Thanks!

**Comment by mitar** [comment]
Then you have a callback for your Meteor method, no? You can use that to know when method finished?

Inside Meteor methods calls to roles API behave like synchronous calls.

**Comment by myexampleusername** [comment]
Ahh, no, that doesn't work.  Why don't you show me a working example?

**Comment by mitar** [comment]
I think it is on you to show me what doesn't work. :-) I sadly do not have time to create examples for you.

**Comment by myexampleusername** [comment]
Are you French? Just wondering...

**Comment by mitar** [comment]
No, why?

**Comment by sveinburne** [comment]
I think a callback would guaranty that the write operation has been done on the server mongodb, but not that it has propagated to the client minimongo...

**Comment by mitar** [comment]
If you have a Meteor method on both client and server side, then on the client side callback is returned when simulation finished, and not when server finishes, so that user gets immediate feedback (latency compensation). If server then fails, client is reverted. If you want this not to happen, define our method only on the server.
