### ISSUE TITLE
Request to check user is in group?

### ISSUE THREAD

**Issue by macroramesh6** [Meteor-Community-Packages/meteor-roles#207]
I am building a multi-domain website. so the users in a particular domain should not access from the another domain. I can create domain name as a `role` is not a wise idea for huge roles. So `groups` without `role` seems good.

I have created a `group` for the user without `role`
`Roles.addUsersToRoles(userId, [], 'domain1');`

How should I check this user in the group like. `Roles.userIsInGroup('domain1')`

**Comment by jerfowler** [comment]
I would give the user at least on role, like `user` or `active`. Then you can check that to see if that user is a currently active user.

`Roles.userIsInRole(userId, 'active', 'domain1')`
or
`Roles.userIsInRole(userId, 'user', 'domain1')`
