### ISSUE TITLE
Access Control to Individual Documents Using Roles

### ISSUE THREAD

**Issue by kirtic** [Meteor-Community-Packages/meteor-roles#212]
If we wanted to implement a google docs like role system where I can grant view, edit, ownership permissions for specific documents to specific users how should I use the roles package to make that work? Should I create a group per document and assign users to viewer, editor roles for that group?

**Comment by mitar** [comment]
Personally I believe that per-document permissions should be stored with the document itself. So this package is not suitable for that.

But people do do that, making group for every document.

**Comment by jonlachlan** [comment]
You can use a string pattern for your groups such as "documentType:docId" to grant users permissions to each document.

For example, you could grant roles for documents of type `issue` or of type `product` as below: 

```
Roles.addUsersToRoles(userId, ['view','edit'], 'issue:' + issueId)
Roles.addUsersToRoles(userId, ['view','edit'], 'product:' + productId)
```

**Comment by alanning** [comment]
I agree with @mitar that per-document permissions should be stored on the document.  I wonder if cloning this package and changing it slightly to work on the Documents collection rather than the Users collection would suit your needs.  Conceptually similar use cases, just different destinations.

So you'd have something like:

`DocPermissions.addUsersToRoles(docId, ['view','edit'], userId)`

**Comment by mitar** [comment]
I am using per-document permissions in my apps but it is a bit trickier than approach here. What you want there is often matching two things: a function which says yes or not for a current user, and a query which selects a document, if it has permission.

**Comment by kirtic** [comment]
That would be really helpful. What would be the ETA for that feature?

**Comment by alanning** [comment]
We aren't planning to add per-document functionality to this package.  I'd
suggest searching atmosphere for other authorization packages.  Some
helpful keywords to search on may be:

access control list
acl
acl-based authorization
per-document authorization

**Comment by mitar** [comment]
Closing this. I think also v3.0 will make it slightly easier to make it per-document, but I still think that per-document permissions should go into documents themselves.
