### ISSUE TITLE
Not getting results from getRolesForUser or getGroupsForUser when providing array

### ISSUE THREAD

**Issue by bmcgonag** [Meteor-Community-Packages/meteor-roles#219]
When I provide an array of groups while trying to get Roles for a user with 

```
Roles.getRolesForUser(this._id, ['Admin', 'GeneralUser'])
```

I just get

```
[]
```

back as the result. 

If I make the request with only one value like

```
Roles.getRolesForUser(this._id, 'Admin')
```

I get the correct value back.  Am I doing something improperly?

**Comment by bmcgonag** [comment]
@alanning Also wanted to ask...when I get back ressults as stated above, I get all roles in comma separated form, but can't seem to figure out how to iterate through them.  

I setup a helper like this.

    getUserRoles: function () {
        return Roles.getRolesForUser( this._id, 'Admin');
    },

Then in template I do something like

    {{#each getUserRoles}}
        {{roles}}
    {{/each}}

No results come up.  

I only get comma separated lest from `{{getUserRoles}}`

Thanks for any help and / or advice.

**Comment by mitar** [comment]
Please provide a reproduction with the latest version of the package. I can reopen the issue then.
