### ISSUE TITLE
how to update users collection

### ISSUE THREAD

**Issue by ketankulkarni** [Meteor-Community-Packages/meteor-roles#228]
1)add role - Roles.addUsersToRole(userId,['rolename']); 
roles was displayed in roles collection

2)but when entered statement in javascript
 Meteor.users.update({_id:"userId"},{$set:{roles:["admin"]}});
this line gives error

**Comment by mitar** [comment]
Which error?

**Comment by ketankulkarni** [comment]
in browser console - 
gpBqdPq2HRhv36JtX  app.js:210:7
update failed: Access denied

**Comment by mitar** [comment]
You might have some permission checks with deny/allow or something else which prevents you to update data on the server from the client directly.
