### ISSUE TITLE
[Suggestion] remove unnecessary dependencies

### ISSUE THREAD

**Issue by saeedjalalisj** [Meteor-Community-Packages/meteor-roles#235]
Hi @mitar @alanning ,
Today I trying to update meteor to 1.4.3.2  and give the below message: 
```
Newer versions of the following indirect dependencies are available:
 * blaze 2.1.9 (2.3.0 is available)           
To update one or more of these packages, pass their names to 
`meteor update`, or just run `meteor update --all-packages`.

 ```
My project is independent from Blaze.js and  based on React.js but your package is depend on Blaze.js.
can you remove Blaze.js dependency please or still make it as a separate package for example `meteor-roles-blaze`?

Thanks for your attention.

**Comment by mitar** [comment]
Yea, Blaze could be made a weak dependency. Care to do PRs for both v1.0 and v2.0?

**Comment by mitar** [comment]
Oh, [Blaze is already a weak dependency](https://github.com/alanning/meteor-roles/blob/master/roles/package.js#L19). So I am not sure what is happening here.

**Comment by saeedjalali1** [comment]
This is my `meteor list` output:
 ```
accounts-base            1.2.15  A user account system
accounts-password        1.3.4  Password support for accounts
alanning:roles           1.2.16  Authorization package for Meteor
aldeed:collection2-core  2.0.0  Core package for aldeed:collection2
ecmascript               0.6.3  Compiler plugin that supports ES2015+ in all .js files
es5-shim                 4.6.15  Shims and polyfills to improve ECMAScript 5 support
jquery                   1.11.10  Manipulate the DOM using CSS selectors
less                     2.7.9  Leaner CSS language
meteor-base              1.0.4  Packages that every Meteor app needs
mobile-experience        1.0.4  Packages for a great mobile user experience
mongo                    1.1.16  Adaptor for using MongoDB and Minimongo over DDP
react-meteor-data        0.2.9  React mixin for reactively tracking Meteor data
reactive-var             1.0.11  Reactive variable
shell-server             0.2.3  Server-side component of the `meteor shell` command.
standard-minifier-css    1.3.4  Standard css minifier used with Meteor apps by default.
standard-minifier-js     1.2.3  Standard javascript minifiers used with Meteor apps by default.
static-html              1.2.0  Define static page content in .html files
tracker                  1.1.2  Dependency tracker to allow reactive callbacks

```

Maybe this dependency is for other packages ?

**Comment by paulincai** [comment]
Hi,

any chance for a separation from jquery?

Tx,
Paul
![screen shot 2018-08-16 at 16 52 59](https://user-images.githubusercontent.com/26188915/44209576-fbf1b480-a174-11e8-9a44-e6c640a33951.png)

**Comment by mitar** [comment]
Blaze is a weak dependency. You can remove it from your project and it will not be forced by this package.

**Comment by paulincai** [comment]
I've got not blaze and no jquery in my packages setup. There is no other way to remove Blaze other than removing it from packages and I am 100% sure I don't have it.
I am past this: https://github.com/meteor/meteor/issues/6844#issuecomment-282188007 and only get Blaze and jquery from the 2 sources listed above.

**Comment by mitar** [comment]
Yes. So `accounts-base` is forcing it, so you have it.

**Comment by mitar** [comment]
I have no idea. Maybe raise the issue on Meteor issue tracker?

**Comment by mitar** [comment]
This needs a better reproduction before it can be acted upon.
