### ISSUE TITLE
getGroupsForUser returns incorrect results for role names containing periods

### ISSUE THREAD

**Issue by mfenwick-house** [Meteor-Community-Packages/meteor-roles#236]
_Role_ name arguments supplied to getGroupsForUser have periods replaced by underscores, when period replacing appears to be intended for _group_ names only.

In such cases, getGroupsForUser returns the groups for a different, similarly named role actually containing underscores instead of periods, or, if such a role does not exist, an empty array.
 
```
Roles.createRole('users.view');
Roles.addUsersToRoles(user._id, 'users.view', group);
Roles.getGroupsForUser(user._id, 'users.view'); // Returns []
```

**Comment by neoromantic** [comment]
Second that, just stumbled on this.

**Comment by payner35** [comment]
+1
