### ISSUE TITLE
what is the proper way to remove a role from a user?

### ISSUE THREAD

**Issue by steveinatorx** [Meteor-Community-Packages/meteor-roles#240]
please include a code sample from latest build thanks

**Comment by MuyBien** [comment]
`Roles.removeUsersFromRoles( Meteor.userId(), '<role-names(s)>', '<role-group>' );`

When we need to remove a user from a role, we can use this. What's unique about this function is that we can pass either a single userId, or, an array. This is handy for doing bulk updates (e.g. removing a deprecated role) on several users.

source : https://themeteorchef.com/tutorials/using-the-roles-package
