### ISSUE TITLE
New user creation

### ISSUE THREAD

**Issue by Taakn** [Meteor-Community-Packages/meteor-roles#246]
When creating new users, not all roles are added to the users. Some roles are being skipped randomly.

**Comment by mitar** [comment]
How are you adding roles to the users?

**Comment by Taakn** [comment]
Roles.setUserRoles(userId, role); 

where my roles are defined here https://github.com/alanning/meteor-roles/issues/223

Maybe when there are too many roles it bugs out and skips roles ?

**Comment by mitar** [comment]
A reproduction would be needed here.
