### ISSUE TITLE
Configure exclusive roles

### ISSUE THREAD

**Issue by merlinpatt** [Meteor-Community-Packages/meteor-roles#250]
Can a configuration option be added to make certain roles mutually exclusive from each other?

**Comment by mitar** [comment]
I think this is something you could manage on your own?

**Comment by merlinpatt** [comment]
I could, but I feel like this is a natural fit for this package.

**Comment by mitar** [comment]
Not sure how to make this extensible though. I think there could be probably many different more complicated conditions you might have which roles can co-exist?

**Comment by mitar** [comment]
A 3rd party extension could provide that.
