### ISSUE TITLE
Update allow-deny@1.0.5 to 1.0.9

### ISSUE THREAD

**Issue by ArthurGerbelot** [Meteor-Community-Packages/meteor-roles#252]
Following the Meteor Allow-Deny Vulnerability Disclosure, the dependency to `allow-deny`  in file `roles/.versions` should be updated to `1.0.9` to fix it.

**Comment by topleft** [comment]
+1

**Comment by alanning** [comment]
Merged into master.  What is the effect of the `roles/.versions` file pointing to the pre-patch version?

**Comment by topleft** [comment]
A vulnerability was found in which a specially formed payload sent over a web socket could gain access to updating docs in the DB.

https://forums.meteor.com/t/meteor-allow-deny-vulnerability-disclosure/39500

**Comment by topleft** [comment]
@alanning Will you update the Atmosphere package to reflect what is currently on master?

**Comment by mitar** [comment]
I am also unsure here if anything should be done. It is a patch bump. Anyone can just update it locally in their app. This package is not preventing that in any way.

**Comment by mitar** [comment]
I think this has been done.
