### ISSUE TITLE
Excluding GLOBAL_GROUP-only users in getUsersInRole

### ISSUE THREAD

**Issue by tdukart** [Meteor-Community-Packages/meteor-roles#257]
I'd like to get a list of users with the `'LOGIN'` privilege for a specific group, but exclude the global group.

Here's my use case: Polly is a superadmin for my app, so she has LOGIN privileges in the GLOBAL_GROUP so she can access all of the clients.

Simon is an administrator for the Acme Anvils group. He would need to be able to administer all of Acme's users. However, because Polly is a superadmin, she'd be listed with the other users.

For now, I'll get around this by writing my own query (which I realized I could do while typing this), but it might become difficult to maintain if anything changes within meteor-roles.

I'm happy to write a PR to implement this, but I've never done any Atmosphere development so it'll take some time. Also, I'm not sure the best way to change the API -- new method (`getUsersInRoleExcludingGlobal`) or a new param to `getUsersInRole`?

**Comment by mitar** [comment]
I think you could add another option to `getUsersInRole` for this.

**Comment by SimonSimCity** [comment]
In case you still need this feature, you can update to `3.x` and use the following code:

```js
Roles.getRolesForUser(user, { onlyScoped: true })
```

I have no plans on integrating this feature in older versions, but PRs are always welcome.
