### ISSUE TITLE
Roles not updating reactively

### ISSUE THREAD

**Issue by jroque-seertech** [Meteor-Community-Packages/meteor-roles#261]
I need to re login for the updated roles to take effect. Is there a way to make in reactive ??

here's my code in publications.js
`Meteor.publish(null, function (){
    return Meteor.roles.find({})
});`

and my code in template
`{{#if isInRole 'view' 'badge_role'}}`

**Comment by mitar** [comment]
This looks like it should work. So a reproduction is needed to demonstrate why it does not for you.
