### ISSUE TITLE
Create new user and  auto login, publish Roles

### ISSUE THREAD

**Issue by lam0620** [Meteor-Community-Packages/meteor-roles#266]
Hi,

Anybody help me.
I'm new meteor.
In my app,  when user login, the system check if user not exist, new user will be created with roles XXX, YYY(Roles.setUserRoles) and then auto login too.
At home page, roles return empty (Roles.getRolesForUser(loggedInUser))
If I log out and login again, I can get correct roles.

How can I get roles of logged in user in case create new user and auto login.
How can I publish created user/roles to client after role creation?

Thanks,
lam0620

**Comment by BobbyWalkerTech** [comment]
Do you still have autopublish on your Meteor installation?  If so, then the publish/subscribe methods that would normally update will not run.

**Comment by lam0620** [comment]
Thanks @BobbyWalkerTech 

autopublish is not a direct dependency in this project.
auto login after Accounts.createUser(XXX) and the roles is empty (as above my question)

Note: When create new user and auto login case
At my development mode, I can get correct roles.
But on my production (built production mode), the roles is empty

Please help!

**Comment by mitar** [comment]
This should work. So a reproduction would be needed if it does not work for you.
