### ISSUE TITLE
extra user definable fields on roles

### ISSUE THREAD

**Issue by maasha** [Meteor-Community-Packages/meteor-roles#275]
Can we have extra fields to hold meta-data. E.g. I would like to have a description field for each role?

```
{
  "_id" : "WzcRA2GzcrnGLeDtB",
  "name" : "SuperUser",
  "meta" : {
    "description" : "User with demi-god powers"
  }
}
```

**Comment by mitar** [comment]
In 2.0 you can add to the collection any other fields you want yourself.
