### ISSUE TITLE
Support for groups with parents

### ISSUE THREAD

**Issue by antonio-goncalves** [Meteor-Community-Packages/meteor-roles#280]
There is any support for groups with parents? It would be useful for this use case

groupA: {name:"StoreA"}
groupB: {name:"StoreB"}
groupC: {name:"StoreCluster",children:["StoreA","StoreB"]}

Roles.addUsersToRoles(joesUserId, ['Manage'], 'StoreCluster');

Roles.userIsInRole(joesUserId, 'Manage', 'StoreA'); // true if considering parent groups
Roles.userIsInRole(joesUserId, 'Manage', 'StoreB'); // true if considering parent groups

**Comment by mitar** [comment]
For which version is this? v1 or v2?

**Comment by SimonSimCity** [comment]
This functionality has already been added in 2.x, as far as I understand from the example. Please ask me to reopen if it's not applicable.
