### ISSUE TITLE
Repository organization

### ISSUE THREAD

**Issue by mitar** [Meteor-Community-Packages/meteor-roles#283]
So continuing discussion from [here](https://github.com/Meteor-Community-Packages/organization/issues/25#issuecomment-536254032), cc @SimonSimCity @sebakerckhof.

I would propose that we have three branches `master`, `v1` and `v2`. Version 3.0 becomes the `master` branch. I would not try to merge those three branches all in `master`. They can diverge. `v1` and `v2` should just contain bugfix releases anyway. If there is anything important we can always cherry-pick between branches.

**Comment by SimonSimCity** [comment]
Agree. I'll give it a go and follow the [git-cactus](https://github.com/Hustle/git-cactus) branching model.

**Comment by SimonSimCity** [comment]
How can I publish a version to atmosphere - or should we add some git-actions for this?

**Comment by alanning** [comment]
I've created a new Meteor org, "roles", and added it as a maintainer of the "alanning:roles" package.

The current members of the roles meteor org are:
alanning, mitar, simonsimcity

@SimonSimCity I think this should give you access to publish.  I'd suggest we get the v1, v2, and master (v3) branches set up and then you can try publishing the new versions.

FYI, the "communitypackages" org is also currently a maintainer of the alanning:roles package so anyone in that org should also be able to publish.

**Comment by mitar** [comment]
> FYI, the "communitypackages" org is also currently a maintainer of the alanning:roles package so anyone in that org should also be able to publish.

Yes, this is a failsafe if all maintainers from `roles` stop responding.

**Comment by Fen747** [comment]
Hi !

Could I be added to the org please, so that I can help with migrating the package faster ? :)

**Comment by mitar** [comment]
@Fen747 thanks for jumping on, but personally I would prefer if this is a bit more coordinated here. It is already three people with three branches. Let's do it slowly. :-)

But I would invite you to jump on any other of pending packages and take action on them? So I think some of potentially unmaintained packages still need maintainers?

**Comment by mitar** [comment]
I also created labels `v1`, `v2`, `v3`, and `version unknown` to tag which versions an issue applies to.

**Comment by mitar** [comment]
I have updated all READMEs in all branches and published new v1 and v2 packages. Now it is all on you @SimonSimCity to push your changes to `master` branch and get v3 out.
