### ISSUE TITLE
Which version should be published on GitHub pages?

### ISSUE THREAD

**Issue by mitar** [Meteor-Community-Packages/meteor-roles#284]
The package has documentation at:

https://meteor-community-packages.github.io/meteor-roles/

Should we organize it by versions? Where should be the job to build it? GitHub Actions?

**Comment by SimonSimCity** [comment]
I just need to run `yuidocjs` and I get the files generated. For me it's just a question of where should it be pushed. If we just have one version, I'd take the latest version - the one on master.

**Comment by mitar** [comment]
I would suggest we force push things to `gh-pages` branch, each version into its own sub-directory. We always clone existing branch, regenerate for a particular version, commit-amend, and force push.

**Comment by SimonSimCity** [comment]
Something I just found in a research:

* https://www.npmjs.com/package/jsdoc-to-markdown - creates markdown for JSDocs
* https://github.com/thlorenz/wicked - creates markdown for JSDocs and upload it to the GitHub wiki.

**Comment by StorytellerCZ** [comment]
Closing this as we will re-work the docs entirely for all MCP packages to unify things.
