### ISSUE TITLE
Add CI to the repository to run tests for all branches/versions

### ISSUE THREAD

**Issue by mitar** [Meteor-Community-Packages/meteor-roles#285]

**Comment by SimonSimCity** [comment]
Updated the branches `master` and `v2` to have npm commands for running tests. We only need to ensure that we have an environment where meteor is installed and we can go ahead calling `npm test`.

**Comment by trudeaua21** [comment]
I think I'm gonna give this a go using GitHub Actions for Hacktoberfest if that's alright - let me know if that's not the route everyone would prefer, or if it's not needed anymore!

**Comment by copleykj** [comment]
I personally think that would be awesome.

**Comment by StorytellerCZ** [comment]
@trudeaua21 any additional works on the CI is welcome! Since we have GitHub Actions running now I'm closing this issue.
