### ISSUE TITLE
Add Typescript declarations

### ISSUE THREAD

**Issue by bbenoist** [Meteor-Community-Packages/meteor-roles#297]
Since Meteor now supports TypeScript, it would be nice to have type definitions on this package.

Documentation: https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html
Template: https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html

**Comment by SimonSimCity** [comment]
Might also be a good time to take this package into TypeScript ... PRs are welcome. Please ping me if you're interested to get started with it.

**Comment by SimonSimCity** [comment]
If we want to stay at plain javascript, some library like [`tsd-jsdoc`](https://www.npmjs.com/package/tsd-jsdoc) might be valuable.

**Comment by diavrank** [comment]
> Might also be a good time to take this package into TypeScript ... PRs are welcome. Please ping me if you're interested to get started with it.

Maybe this can be of help https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/meteor-roles/index.d.ts to update it to **version 3** . (That is the type definitions for **v1.2.14**)

**Comment by wallind** [comment]
Does anyone still have interest in moving this to support v3.2.3? I badly need this library to work with that version and below and would be willing to contribute

**Comment by wallind** [comment]
https://github.com/wallind/DefinitelyTyped/tree/bump-supported-version-to-2.1.0-meteor-roles

To get the ball rolling I'm working on getting @types/meteor-roles to support 2.1.0 on the branch above

**Comment by diavrank** [comment]
is there any newness about this?

**Comment by Clovel** [comment]
> https://github.com/wallind/DefinitelyTyped/tree/bump-supported-version-to-2.1.0-meteor-roles
> 
> To get the ball rolling I'm working on getting @types/meteor-roles to support 2.1.0 on the branch above. If anyone wants to participate hit me up

Got any updates on this ?

**Comment by StorytellerCZ** [comment]
With v3.6.2 types should be all set. In the future version of roles package we should move to TypeScript.

**Comment by bobo96run** [comment]
Just for reference, once the `alanning:roles` package has been added to the Meteor project, you need to either start it or execute `meteor lint` to have types set up and available, as explained in the [docs](https://github.com/zodern/meteor-types?tab=readme-ov-file#meteor-apps) of `zodern:types` (which this package depends on):
> The type definitions are updated whenever your app is built. You can also update the types directly by running `meteor lint`.
