### ISSUE TITLE
Get only parent roles.

### ISSUE THREAD

**Issue by danyhiol** [Meteor-Community-Packages/meteor-roles#301]
Is there any function to get only user's `parent roles`? Something like `Roles.getAllParentRoles(userId);`

**Comment by SimonSimCity** [comment]
What you mean by `parent roles`?

In case you mean the roles assigned to a user, you can use: `Roles.getRolesForUser(user, { onlyAssigned: true })`

https://github.com/Meteor-Community-Packages/meteor-roles/blob/master/roles/roles_common.js#L710

**Comment by danyhiol** [comment]
Exactly what I was looking for. 
Thanks.
