### ISSUE TITLE
E11000 duplicate key error collection

### ISSUE THREAD

**Issue by DeanKamali** [Meteor-Community-Packages/meteor-roles#307]
I'm trying to create a number of new roles and I keep getting this error

```
> Roles.createRole('admin');
MongoError: E11000 duplicate key error collection: meteor.roles index: name_1 dup key: { name: null }


> Roles.createRole('provider');
MongoError: E11000 duplicate key error collection: meteor.roles index: name_1 dup key: { name: null }
```

`alanning:roles@3.1.0`

Any ideas?

**Comment by SimonSimCity** [comment]
Does this happened after updating your roles collection from 1.x, or at least you still have the index on the `name` field still on your `roles` collection?

**Comment by DeanKamali** [comment]
Yes, it started to happen after the upgrade, I'm not sure what version I had before 1.x or 2.x checking git, it only says `alanning:roles` from before. 

I only have 3 roles (admin, patient, provider) in roles collection 

```
{
    "_id" : "aWJYaTEjbLzYCJTdu",
    "name" : "admin"
},
{
    "_id" : "owAd3tYj5ZtKWCLTn",
    "name" : "patient"
},
{
    "_id" : "ssYDT95Gcv2xJvKBs",
    "name" : "provider"
}

```

**Comment by SimonSimCity** [comment]
The roles you show me also are according to the first version of this package. Please run the update script before running any additional commands. First update to `v2.0` and then to `v3.0`. I advise you to do it in two separate steps as proposed in the readme (https://github.com/Meteor-Community-Packages/meteor-roles#migration-to-30).

Please keep in mind that the update to version 1.x will still leave the old roles in place, which you might have to remove manually - as of the time now ...

This is in case you want to fall back to the old database design.

- Related to https://github.com/Meteor-Community-Packages/meteor-roles/issues/300

**Comment by SimonSimCity** [comment]
Let me know if there's anything else, but this should solve it. Please ask to reopen if it doesn't.

**Comment by DeanKamali** [comment]
Well, here is what I ended up doing, I dropped `roles` and `role-assignment` and it got re-created when I added new roles. 

Things started to work, however, I faced an issue with `getUsersInRole` returning an empty array all the time. 

Turned out that my local MongoDB use newer version 4.2 and by downgrading to version 4.0.10
`getUsersInRole` method started to work.

**Comment by SimonSimCity** [comment]
Oh! Thanks for notifying! Could you create a new issue for this?

**Comment by jamauro** [comment]
If anyone else comes across the same problem, the sequence of upgrading is important. 

1. Type `meteor remove alanning:roles` and then `meteor add alanning:roles@2.0.0`
2. Run the migration script in the shell https://github.com/Meteor-Community-Packages/meteor-roles#migration-to-30
3. Then update your code e.g. add things like `Roles.createRole`. (If you do this step before the migration script you'll get the duplicate error key.)
