### ISSUE TITLE
suggestion: getRolesForUser method have option to return scope roles only

### ISSUE THREAD

**Issue by Slavrix** [Meteor-Community-Packages/meteor-roles#313]
It would be useful to extend the getRolesForUser method to allow for it to return roles for the scope only, if a scope is provided.

currently if you provide a scope, it returns an array that includes the roles for that scope AND the global scope.

Use Case:
Administrators of a Scope are allowed to create their own roles/permissions and name them what they choose.
We don't want the Scope Admins to be able to view global roles that are included by developers. eg super administrators, vip users, early adoptor flags etc.

**Comment by SimonSimCity** [comment]
Isn't this covered by the setting `onlyScoped`?

https://github.com/Meteor-Community-Packages/meteor-roles/blob/32c230ded9cb92b27a3485d143cabf2732fef186/roles/roles_common.js#L706-L723

**Comment by Slavrix** [comment]
Probably helps if I read things fully right..... :D
