### ISSUE TITLE
TypeError: Package.alanning:roles.Roles._forwardMigrate is not a function

### ISSUE THREAD

**Issue by Ajaay** [Meteor-Community-Packages/meteor-roles#315]
Hi,

Trying to upgrade from v1 to v2 but the forwardMigrate function does not appear to be available and gives me this error:

Package['alanning:roles'].Roles._forwardMigrate()
TypeError: Package.alanning:roles.Roles._forwardMigrate is not a function
    at evalCommandPromise.then (packages/shell-server/shell-server.js:249:21)
    at runBound (domain.js:314:12)
    at bound (domain.js:301:14)
    at defaultEval (repl.js:240:29)
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at repl:1:-29

Here's what looks to be available:

> Package['alanning:roles'].Roles
{ GLOBAL_GROUP: '__global_roles__',
  createRole: [Function: createRole],
  deleteRole: [Function: deleteRole],
  addUsersToRoles: [Function: addUsersToRoles],
  setUserRoles: [Function: setUserRoles],
  removeUsersFromRoles: [Function: removeUsersFromRoles],
  userIsInRole: [Function: userIsInRole],
  getRolesForUser: [Function: getRolesForUser],
  getAllRoles: [Function: getAllRoles],
  getUsersInRole: [Function: getUsersInRole],
  getGroupsForUser: [Function: getGroupsForUser],
  '_update_$set_fn': [Function: _update_$set_fn],
  '_update_$addToSet_fn': [Function: _update_$addToSet_fn],
  _updateUserRoles: [Function: _updateUserRoles] }

Thanks

**Comment by SimonSimCity** [comment]
Please first update your application to v2 and run the code again. If it still doesn't work, please run the following code either in your application code or from the meteor console:

```js
import("meteor/alanning:roles").then(p => {
  console.log("Start migration ...")
  p.Roles._forwardMigrate();
  console.log("Migration completed.")
})
```

This code is just an alternative way of calling the same functionality. It should work either way.

**Comment by Ajaay** [comment]
Sorry that's pretty obvious isn't it! Done and on v3 now. Thanks
