### ISSUE TITLE
Could add custom fields? 

### ISSUE THREAD

**Issue by thearabbit** [Meteor-Community-Packages/meteor-roles#325]
Could add custom fields? for example `type field: core, account, loan....`

**Comment by SimonSimCity** [comment]
@thearabbit as long as you understand what the fields and their relations are, you're all free to go. The set is put together in a way that it should be easy for you to do these things.

**Comment by thearabbit** [comment]
thanks for your reply.
Could you example to add `new field` on roles collection with `Roles.createRole, Roles.addRolesToParent`?

**Comment by SimonSimCity** [comment]
Well, the command `Roles.createRoles()` returns the `_id` property of the newly inserted document, which you can use to adjust to your needs, if you really want to change the role ...

Btw - which version of this package are you refering to?

**Comment by thearabbit** [comment]
It mean that
```js
Meteor.roles.update(..........)
```

**Comment by SimonSimCity** [comment]
Yeah, just use the id you got as a return value of `Roles.createRoles()`.

**Comment by thearabbit** [comment]
thanks 👍
