### ISSUE TITLE
Meteor.roles instanceof Mongo.Collection is false

### ISSUE THREAD

**Issue by s7dhansh** [Meteor-Community-Packages/meteor-roles#328]
Both `Meteor.roles/roleAssignment` are somehow not the instances of `Mongo.Collection`.

My core problem is that I am unable to run aggregation on them, despite adding `aggregate` to the Mon.go.collection prototype. I am able to use the same on Meteor.users (and it also shows to be the instance of Mongo.Collection).

What could be the reason for this? Can some one kindly help?

**Comment by SimonSimCity** [comment]
I expect this to be a problem related to some other extensions you have installed. If you do see this problem also on a plain installation of Meteor, please upload a project to github which I can check out and do some investigation on.

**Comment by StorytellerCZ** [comment]
I'm closing this issue because we haven't heard anything from the original poster for a while.
#344 might address this in the future.
