### ISSUE TITLE
Roles not defined - Add Users To Roles

### ISSUE THREAD

**Issue by wbashir** [Meteor-Community-Packages/meteor-roles#33]
``` Javascript
Roles.addUsersToRoles(userId, roles);
```

That method call when ran from the server is returning an error:

`ReferenceError: Roles is not defined`

Is there anything that has changed? , I am using the latest version '1.2.8`

**Comment by pvtulsiram538** [comment]
HI ,
I also got the same error can you tell me how you removed and add the smart.json

**Comment by alanning** [comment]
@pvtulsiram538, if you are using meteorite (which users smart.json) you can do:

```
$ mrt remove roles
$ mrt add roles
```

If you are running Meteor 1.0 or higher, you don't need the smart.json file or meteorite.  Check that you are using the latest version of `alanning:roles`, v1.2.14.
