### ISSUE TITLE
Problem with Meteor.roleAssignment and typescript

### ISSUE THREAD

**Issue by FoudreNoire26i** [Meteor-Community-Packages/meteor-roles#338]
Hi,
I'm trying to use meteor-roles package, but i faced a problem : Roles.userIsInRole(myId, 'admin')) always return false in client side.
I read that I had to publish Meteor.roleAssignement, but I can't because I use typescript and roleAssignment is undefined.
Can someone help me ? 
<img width="1022" alt="Capture d’écran 2021-06-29 à 17 28 25" src="https://user-images.githubusercontent.com/63561849/123825696-6bb1b300-d8ff-11eb-80b3-b37b72ac3e64.png">

Thanks

**Comment by FoudreNoire26i** [comment]
Hi,
I finally find a hack by myself. I keep this issue open, if anyone has a better idea (or if the maintainer want to close it ;)), but this is the best solution I found today.
`
Meteor.publish(null, function (){
    var myId = Meteor.userId()
    if (myId && Roles.userIsInRole(myId, 'admin')) {
        return [Meteor.roles.find(), (Meteor as any).roleAssignment.find()]
    } else {
        return this.ready()
    }
});
`

**Comment by StorytellerCZ** [comment]
We will have to figure out how to update the Typescript typings for this. For right now you should be able to supress the warning with `// @ts-ignore`

**Comment by StorytellerCZ** [comment]
Here is the types package, but we'll need to udpate it: https://www.npmjs.com/package/@types/meteor-roles

**Comment by danyhiol** [comment]
You can just add it to your `meteor` **namespace**: `const roleAssignment: Mongo.Collection<Roles.Role>;`.
This is if the type package has not yet been updated.

**Comment by StorytellerCZ** [comment]
@FoudreNoire26i @danyhiol please check the latest version. Types have been added recently.

**Comment by bruceborrett** [comment]
I have the latest version installed and I can see the types being declared if I look at the definitions file in the installed package source, but for some reason I am still getting the same error. Are they perhaps being declared incorrectly? Or am I doing something wrong?

**Comment by StorytellerCZ** [comment]
This is the current declaration in the types for the problematic variables:
```
declare namespace Meteor {
  var roles: Mongo.Collection<Roles.Role>
  var roleAssignment: Mongo.Collection<Roles.RoleAssignment>
}
```

**Comment by bruceborrett** [comment]
If I do:

`import { Meteor } from 'meteor/alanning:roles;`

Then I get the correct types, but I lose all of the other Meteor types. Perhaps this is an issue with the way zodern:types handles these d.ts files because it seems the Meteor namespace is not being extended correctly.

**Comment by bruceborrett** [comment]
Looks like this is the correct definition:

```
declare module 'meteor/meteor' {
  namespace Meteor {
    const roles: Mongo.Collection<Roles.Role>
    const roleAssignment: Mongo.Collection<Roles.RoleAssignment>
  }
}
```

With the above everything works as expected.
