### ISSUE TITLE
Meteor 2.4 compatibility: _ensureIndex has been deprecated (v3.3.0)

### ISSUE THREAD

**Issue by daolutions** [Meteor-Community-Packages/meteor-roles#343]
With the new mongo package in Meteor 2.4 Meteor.roleAssignment._ensureIndex seems to be  deprecated:
`_ensureIndex has been deprecated, please use the new 'createIndex' instead, index: {"user._id":1,"inheritedRoles._id":1,"scope":1}
_ensureIndex has been deprecated, please use the new 'createIndex' instead, index: {"user._id":1,"role._id":1,"scope":1}
_ensureIndex has been deprecated, please use the new 'createIndex' instead, index: {"role._id":1}
_ensureIndex has been deprecated, please use the new 'createIndex' instead, index: {"scope":1,"user._id":1,"inheritedRoles._id":1}
_ensureIndex has been deprecated, please use the new 'createIndex' instead, index: {"inheritedRoles._id":1}
_ensureIndex has been deprecated, please use the new 'createIndex' instead, index: {"children._id":1}`

**Comment by StorytellerCZ** [comment]
There is already a PR ready for it that is now being reviewed. #341
