### ISSUE TITLE
API docs linked to old version of codes

### ISSUE THREAD

**Issue by minhna** [Meteor-Community-Packages/meteor-roles#349]
when I looked for `getRolesForUser` function, it send me to the page:
https://meteor-community-packages.github.io/meteor-roles/classes/Roles.html#method_getRolesForUser
when click on the source code, this is the page:
https://meteor-community-packages.github.io/meteor-roles/files/roles_roles_common.js.html#l366

```
/**
   * Retrieve users roles
   *
   * @method getRolesForUser
   * @param {String|Object} user User Id or actual user object
   * @param {String} [group] Optional name of group to restrict roles to.
   *                         User's Roles.GLOBAL_GROUP will also be included.
   * @return {Array} Array of user's roles, unsorted.
   */
  getRolesForUser: function (user, group) {
```

I believe this is old version of code.

**Comment by StorytellerCZ** [comment]
I have updated the docs site. It now has the correct code and comments from the latest version. Though we will have to make a new docs site as this one will not cut it going forward.
