### ISSUE TITLE
cannot add data into role-assignment

### ISSUE THREAD

**Issue by 113475** [Meteor-Community-Packages/meteor-roles#362]
may I know what is the proper way to fetch role-assignment data from the database and add data to role-assignment. My code only create the role-assignment collection in database but never add data into it. Also may I know what is the proper way to fetch the user-role data from db?
Does I need to set up any publish for the role-assignment? 

Here is my code:
```
import { Meteor } from 'meteor/meteor';
import { BinRoles } from './BinRoles';

Roles.createRole(BinRoles.ADMIN, { unlessExists: true });

Meteor.startup(() => {
  const user = Meteor.users.findOne({ email: '12313@gmail.com' });
  if (!user || Roles.userIsInRole(user._id, BinRoles.ADMIN)) {
    return;
  }

  Roles.addUsersToRoles(user._id, BinRoles.ADMIN);
});

```

and also for the createRole function, as I check in roles_common.js it can accept two parameters, however when I use it only accept one param.

**Comment by StorytellerCZ** [comment]
Make sure to import the Roles object:
```
import { Roles } from 'meteor/alanning:roles'
```

Also where are you running that code? On the client or server?
On the first look your code looks fine.

**Comment by 113475** [comment]
Thanks, the problem has been solved
