### ISSUE TITLE
Meteor.roleAssignment, error: Property 'roleAssignment' does not exist on type 'typeof Meteor'.

### ISSUE THREAD

**Issue by 113475** [Meteor-Community-Packages/meteor-roles#363]
system say error about the role assignment. What should I do to solve this problem?

**Comment by copleykj** [comment]
Could be helpful to provide the error here.

**Comment by StorytellerCZ** [comment]
@113475 can you please provide us the exact error message from console, or even better a reproduction of the issue?

**Comment by StorytellerCZ** [comment]
A possible issue could be that you are trying to access this before `Meteor.startup`, hence before everything is initialized.

**Comment by 113475** [comment]
Thanks for you all, the problem has been solved.
