### ISSUE TITLE
TypeError: Cannot set property 'isCalledFromAsync' of undefined ...

### ISSUE THREAD

**Issue by PatrickKaim** [Meteor-Community-Packages/meteor-roles#370]
Error occurs when starting to run the app.

**How to recreate the issue:**
```
% meteor create rolesTest --vue
% cd rolesTest
% meteor
``` 
**Runs fine. Now let's add some packages:**
```
% meteor add accounts-password
% meteor add accounts-passwordless
% meteor add planning:roles
% meteor
```
**Error occurs.**

See full error output here: [Error-alanning-roles.txt](https://github.com/Meteor-Community-Packages/meteor-roles/files/12049871/Error-alanning-roles.txt)

Creating a project with v3.4.0 has no issues just newly released v3.5.0

**Comment by PatrickKaim** [comment]
ps. trying to add the previous version doesn't work (or I am doing it wrong).

```
% meteor add alanning:roles@3.4.0

Changes to your project's package version selections:
                                              
alanning:roles  added, version 3.5.0          
zodern:types    added, version 1.0.9

alanning:roles: Authorization package for Meteor
```

Just tells me v3.5.0 is added

**Comment by rioadrian** [comment]
Hi, I'm get the same error please update any information about this bugfix status. Thanks in advance

**Comment by copleykj** [comment]
Looks like the when index creation functions are assigned to variables they lose their context. I've created a pull request to bind the functions to their respective objects before assignment to new variables.
