### ISSUE TITLE
Alpha 3 not compatible with Meteor 3 rc2

### ISSUE THREAD

**Issue by carlosalvidrez** [Meteor-Community-Packages/meteor-roles#398]
Got this dependency error after upgrading to Meteor 3 rc2:

`blaze@2.9.0 <- alanning:roles 4.0.0-alpha.3`

**Comment by jankapunkt** [comment]
Hey @carlosalvidrez please try [v4.0.0-alpha.4](https://packosphere.com/alanning/roles/4.0.0-alpha.4)

**Comment by carlosalvidrez** [comment]
That worked, thank you!
