### ISSUE TITLE
insert failed: Access denied when calling setUserRoles or addUsersToRoles

### ISSUE THREAD

**Issue by ghost** [Meteor-Community-Packages/meteor-roles#40]
I'm getting the error `insert failed: Access denied` in Chrome's dev tools whenever I use setUserRoles or addUsersToRoles. They still work, though - my test user is updated correctly every time.

**Comment by sferoze** [comment]
I am getting this issue. Why can I not add user to roles client side? As long as I have my allow rules setup it should work

**Comment by mitar** [comment]
Using allow rules is getting deprecated in Meteor. Create Meteor methods and call roles functions from there.

**Comment by sferoze** [comment]
@mitar Oh really? no more allow deny rules. very interesting. Do you know of any documentation where they provides this update and what will replace it?

**Comment by mitar** [comment]
See here some information: https://github.com/meteor/meteor/pull/5559

You just do Mongo operations from inside Meteor methods. This is the recommended way.
