### ISSUE TITLE
problem installing examples... 

### ISSUE THREAD

**Issue by garrilla** [Meteor-Community-Packages/meteor-roles#46]
following the `examples` instructions I get a an app that launches to an error... 

`
dev@sbox2:~/projects$ git clone https://github.com/alanning/meteor-roles.git
Cloning into 'meteor-roles'...
remote: Reusing existing pack: 929, done.
remote: Total 929 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (929/929), 271.72 KiB | 222.00 KiB/s, done.
Resolving deltas: 100% (470/470), done.
Checking connectivity... done
dev@sbox2:~/projects$ cd meteor-roles/examples/router
dev@sbox2:~/projects/meteor-roles/examples/router$ meteor
Installing Meteor 0.7.2:
- 'meteor' build tool (version 8e197f29c5)
- Package updates: accounts-base accounts-facebook accounts-github
  accounts-google accounts-meetup accounts-meteor-developer accounts-oauth
  accounts-password accounts-twitter accounts-ui accounts-ui-unstyled
  accounts-weibo deps domutils facebook facts github google handlebars htmljs
  http less livedata liverange madewith meetup meteor meteor-developer
  minifiers minimongo mongo-livedata oauth1 preserve-inputs
  service-configuration showdown spark spiderable standard-app-packages stylus
  templating test-helpers test-in-browser twitter universal-events weibo

[[[[[ ~/projects/meteor-roles/examples/router ]]]]]

=> Started proxy.
=> Meteor 0.8.2 is available. Update this project with 'meteor update'.
=> Started MongoDB.
=> Errors prevented startup:

While building the application:
error: no such package: 'router'
error: no such package: 'roles'

=> Your application has errors. Waiting for file change.
`

Any advice?

**Comment by Ethaan** [comment]
Hi @alanning i just create this [demo](http://leaderboard-roles.meteor.com) did you think its good to point to newcomers, or should i add more features? like publishing data only to autorhized accounts etc?

**Comment by alanning** [comment]
Hi @Ethaan, I like the concept.  Can you post the link to the source?

**Comment by Ethaan** [comment]
[Source](https://github.com/Ethaan/leadboard-roles) i can improve it, just tell me where =p

**Comment by alanning** [comment]
@Ethaan, I'm on vacation this week but looking forward to checking it out once we get back.  Thanks!
