### ISSUE TITLE
Exception while invoking method 'adminAddUserToRole' Error: Missing 'users' param

### ISSUE THREAD

**Issue by mathieutozer** [Meteor-Community-Packages/meteor-roles#62]
I'm using the yogiben:admin package which uses roles, and when I try to add a new user to a role by pushing the role name button, the console logs

Error invoking Method 'adminAddUserToRole': Internal server error [500] 

and the server errors with 

Exception while invoking method 'adminAddUserToRole' Error: Missing 'users' param

I am publishing the roles to the client with 

Meteor.publish(null, function () {
   return Meteor.roles.find({});
});

And also publishing user documents with 

return Meteor.users.find({}, {'emails': true, 'profile':true, 'roles':true});

in server/publish.js

I am not using groups afaik, and the roles functionality works (only admins are able to enter the admin panel).

What could be going on? Am I missing a step?

**Comment by reduxdj** [comment]
I'm having a similar issue with the faceook login, where the iD is null

**Comment by alanning** [comment]
Hi @reduxdj.  `Roles` needs the `_id` of an account which already exists in the `users` collection.  You'll need to make sure the usage of the `roles` package takes place after the user record has been created.
