### ISSUE TITLE
Sometimes roles are not add using Roles.addUsersToRoles();

### ISSUE THREAD

**Issue by frozeman** [Meteor-Community-Packages/meteor-roles#64]
Hi

I call the following inside a method on the server:

```
 Roles.addUsersToRoles(userId, ['create-delete'], teamId);
```

One line later i update the same user document.

Sometimes its not adding the role at all? Could this have to do with trying to write into the same user object? Or some kind of roundtrip(check on other collection) which fails, which you plugin does?

**Comment by vaughnkoch** [comment]
I have a repro - let me know if you want me to add additional instrumentation.
var user = Meteor.users.findOne(userId);  // userId supplied earlier in code
console.log('adding user');

Roles.addUsersToRoles(user, ['foobar']);
console.log(user.roles);

user = Meteor.users.findOne(userId);
console.log(user.roles);

=> Meteor server restarted
I20150120-13:28:55.307(-8)? adding user
I20150120-13:28:55.325(-8)? undefined
I20150120-13:28:55.328(-8)? [ 'foobar' ]

@alanning, as you pointed out earlier, you can ensure that the data's there by reloading the user object, but shouldn't it work without requiring another mongo round-trip? A simple solution would just be to set the roles object on the user obj directly within addUsersToRoles.

**Comment by alanning** [comment]
Hi @vaughnkoch, I don't think this is the same issue as what @frozeman reported since his is using `userId` rather than the user object.  But I do think its worth discussing what you pointed out.  Can you open a new ticket and I'll respond there, please?
